services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: ['npm', 'start']

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ['npm', 'run', 'dev', '--', '--host']
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
